import '@/styles/globals.css'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import Head from 'next/head'
export default function App({ Component, pageProps }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='min-h-[100vh] flex flex-col gap-20 bg-[#d44351]'>

        <Header />
        <Component {...pageProps} />
        <Footer />
      </div>
    </div>
  )
}
